name: Android CI
on: [push, pull_request]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Tests & Build apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Tests & Build apk
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: |
            buildSrc/**/Deps.kt
          concurrent: true
          arguments: |
            spotlessCheck
            testDebug
            assembleRelease

      - name: Copy build reports
        if: always()
        run: |
          mkdir -p build-reports
          find . -name "reports" -exec cp -r {} build-reports/ \;
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: build-reports

      - name: Copy test results
        if: always()
        run: |
          mkdir -p junit
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} junit/ \;
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: junit-results
          path: junit

      - name: Upload app-release
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk